#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login_check:
  path: /login_check
doctor_controllers:
  resource: ../src/Controller/Doctor
  type: annotation
  prefix: /doctor
patient_controllers:
  resource: ../src/Controller/Patient
  type: annotation
  prefix: /patient
search_users:
  path: /search-users
  controller: App\Controller\Doctor\OrdonnanceController::searchOrdonnance